default: &default
  # Database configuration
  DB_PORT: "5432"
  DB_POOL: <%= ENV.fetch("RAILS_MAX_THREADS") { "5" } %>
  DB_HOST: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  # Mailer configuration
  SMTP_ADDRESS: "smtp email address"
  SMTP_DOMAIN: "smtp email domain"
  SMTP_PORT: "587"
  SMTP_USERNAME: "test@decidim.com"
  SMTP_PASSWORD: "1234asdf"
  # GeoCoder configuration (developer.here.com)
  GEOCODER_LOOKUP_APP_ID: "here_app_id"
  GEOCODER_LOOKUP_APP_CODE: "here_app_code"
  DECIDIM_ENABLE_HTML_HEADER_SNIPPETS: "true"

  HOST: "localhost"

development:
  <<: *default
  DB_DATABASE: "stratified_sortitions_development"
  DB_USERNAME: "ruben"
  DB_PASSWORD: "12345678"

test:
  <<: *default
  TEST_DB_DATABASE: "stratified_sortitions_test"
  TEST_DB_USERNAME: "ruben"
  TEST_DB_PASSWORD: "12345678"

integration:
  <<: *default
  # secrets
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>

staging:
  <<: *default

production:
  <<: *default
